"""sprint2_chat_infrastructure

Revision ID: fd0142a9bafd
Revises: 30af47a0b05f
Create Date: 2026-06-06 10:42:48.578000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd0142a9bafd'
down_revision: Union[str, None] = '30af47a0b05f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_logs',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('input_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('output_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('latency_ms', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cost', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_logs_id'), 'usage_logs', ['id'], unique=False)
    op.create_index(op.f('ix_usage_logs_user_id'), 'usage_logs', ['user_id'], unique=False)
    op.add_column('chat_messages', sa.Column('model_name', sa.String(length=100), nullable=True))
    op.add_column('chat_messages', sa.Column('input_tokens', sa.Integer(), server_default='0', nullable=False))
    op.add_column('chat_messages', sa.Column('output_tokens', sa.Integer(), server_default='0', nullable=False))
    op.add_column('chat_messages', sa.Column('latency_ms', sa.Integer(), server_default='0', nullable=False))
    op.add_column('chat_sessions', sa.Column('system_prompt', sa.Text(), nullable=True))
    op.add_column('chat_sessions', sa.Column('temperature', sa.Float(), server_default='0.7', nullable=False))
    op.add_column('chat_sessions', sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('chat_sessions', sa.Column('last_message_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'last_message_at')
    op.drop_column('chat_sessions', 'is_archived')
    op.drop_column('chat_sessions', 'temperature')
    op.drop_column('chat_sessions', 'system_prompt')
    op.drop_column('chat_messages', 'latency_ms')
    op.drop_column('chat_messages', 'output_tokens')
    op.drop_column('chat_messages', 'input_tokens')
    op.drop_column('chat_messages', 'model_name')
    op.drop_index(op.f('ix_usage_logs_user_id'), table_name='usage_logs')
    op.drop_index(op.f('ix_usage_logs_id'), table_name='usage_logs')
    op.drop_table('usage_logs')
    # ### end Alembic commands ###
