"""add_subscription_columns

Revision ID: eb07b67652a7
Revises: 8b9d3b76cfda
Create Date: 2026-06-08 15:23:07.068090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb07b67652a7'
down_revision: Union[str, None] = '8b9d3b76cfda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('subscription_plan', sa.String(length=50), server_default='FREE', nullable=False))
    op.add_column('user_settings', sa.Column('subscription_status', sa.String(length=50), server_default='FREE', nullable=False))
    op.add_column('user_settings', sa.Column('billing_cycle', sa.String(length=50), server_default='yearly', nullable=False))
    op.add_column('user_settings', sa.Column('subscription_started_at', sa.DateTime(), nullable=True))
    op.add_column('user_settings', sa.Column('subscription_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'subscription_expires_at')
    op.drop_column('user_settings', 'subscription_started_at')
    op.drop_column('user_settings', 'billing_cycle')
    op.drop_column('user_settings', 'subscription_status')
    op.drop_column('user_settings', 'subscription_plan')
    # ### end Alembic commands ###
