"""add_role_intelligence_layer

Revision ID: caa3239d6169
Revises: 8fe160e92d03
Create Date: 2026-06-09 11:30:33.415065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caa3239d6169'
down_revision: Union[str, None] = '8fe160e92d03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_usage',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('messages_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tokens_used', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sessions_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_usage_id'), 'role_usage', ['id'], unique=False)
    op.create_index(op.f('ix_role_usage_user_id'), 'role_usage', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('default_role', sa.String(length=100), server_default='general', nullable=False),
    sa.Column('default_persona', sa.String(length=100), server_default='teacher', nullable=False),
    sa.Column('experience_level', sa.String(length=50), server_default='beginner', nullable=False),
    sa.Column('learning_style', sa.String(length=50), server_default='mixed', nullable=False),
    sa.Column('career_goal', sa.String(length=255), server_default='fullstack', nullable=False),
    sa.Column('preferred_language', sa.String(length=100), server_default='english', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preferences_id'), 'user_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=True)
    op.add_column('chat_sessions', sa.Column('role_type', sa.String(length=100), server_default='general', nullable=False))
    op.add_column('chat_sessions', sa.Column('persona_type', sa.String(length=100), server_default='teacher', nullable=False))
    op.create_index(op.f('ix_chat_sessions_role_type'), 'chat_sessions', ['role_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_sessions_role_type'), table_name='chat_sessions')
    op.drop_column('chat_sessions', 'persona_type')
    op.drop_column('chat_sessions', 'role_type')
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_index(op.f('ix_user_preferences_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_role_usage_user_id'), table_name='role_usage')
    op.drop_index(op.f('ix_role_usage_id'), table_name='role_usage')
    op.drop_table('role_usage')
    # ### end Alembic commands ###
